### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by adrianiskandar** [mklabs/yarn-completions#1]
After installing globally using:
npm i -g yarn-completions

then typing yarn + tab shows:

```
yarn module.js:457
    throw err;
    ^

Error: Cannot find module '../src/cli'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/adcaballero/.nvm/v6.6.0/lib/node_modules/yarn-completions/bin/yarn-completions.js:3:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
module.js:457
    throw err;
    ^
```

**Comment by mklabs** [comment]
Weird, it looks like the src folder which is babel transpiled code is not found, let me check that.

**Comment by mklabs** [comment]
My guess is that I .gitignored the src/ folder without adding an .npmignore, so npm didn't published the src/ folder... My bad.

Thanks for opening this issue.

**Comment by mklabs** [comment]
@adrianiskandar should be fixed now
