### ISSUE TITLE
yarn add autocomplete errors

### ISSUE THREAD

**Issue by samhh** [mklabs/yarn-completions#4]
`yarn add [tab key]` yields the following error:

```
throw err;
    ^

Error: Cannot find module 'got'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/samhh/.yarn-config/global/node_modules/yarn-completions/src/completions/add.js:3:11)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
```

**Comment by mklabs** [comment]
Thanks for the feedback. Should be solved with 0.0.6.

This is the result of me doing test on the add completions and publishing the src folder with a completion handler for the add command.

For the record, I was trying to use npm search to autocomplete package name but decided to not go for it.
